imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# Doctrine Configuration
doctrine:
    dbal:
        url: '%env(HEROKU_POSTGRESQL_YELLOW_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

monolog:
    handlers:
        main:
            type: stream
            action_level: error
            handler: nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
